TMRS-24: Handle arguments with getopt
- Updated readme
- Updated help option for each command where needed
- Removed some dead code
- Use same structure everywhere
- Removed if [ -n replaced with if ! [ -z
- Added -f and --force-with-lease to push-feature.
- Added -f and --local_only to remove-feature.
- Added -s and -u to status-all.
- Fixed push-feature to work as git push, at least partly
- Fixed install script to show feedback to user
- Fixed squash-feature bug
- Fixed commit-feature so that it can work without -m option.

diff --git a/bin/git-checkout-branch b/bin/git-checkout-branch
--- a/bin/git-checkout-branch
+++ b/bin/git-checkout-branch
@@ -13,17 +13,6 @@ print_help()
 	print_info "usage: git checkout-branch <branch>"
 }
 
-checkout_root()
-{
-	print_info "Checking out $branch branch in root"
-	git checkout $branch
-	if [ $? -gt 0 ]
-	then
-		return 1
-	fi
-	return 0
-}
-
 checkout()
 {
 	print_info "Checking out $branch branch in $1"
@@ -47,27 +36,40 @@ checkout_submodules()
 	done
 }
 
-check_parameters()
-{
-	if [ -z $1 ]
-	then
-		print_error "<branch> is required"
-		print_help
-		exit 1
-	fi
-	
-	if [ "$1" == "-h" ]
-	then
-		print_help
-		exit 0
-	fi
-}
-
 set_tabs
 
-branch=$1
+SHORT=h
 
-check_parameters "$1"
+# read the options
+OPTS=$(getopt -s sh --options $SHORT --name "$0" -- "$@")
 
-checkout_root && 
+if [ $? != 0 ] ; then echo "Failed to parse options...exiting." >&2 ; exit 1 ; fi
+
+eval set -- "$OPTS"
+
+# extract options and their arguments into variables.
+while true ; do
+  case "$1" in
+	-h )
+      print_help
+	  exit 0
+      shift
+      ;;
+    -- )
+	  branch=$2
+	  if [ -z $branch ]
+	  then
+		print_warning "<branch> must be provided"
+		exit 1
+	  fi
+	  shift 2
+      break
+      ;;
+    *)
+      break
+      ;;
+  esac
+done
+
+checkout "root" && 
 checkout_submodules
diff --git a/bin/git-clone-all b/bin/git-clone-all
--- a/bin/git-clone-all
+++ b/bin/git-clone-all
@@ -10,25 +10,45 @@ print_help()
 	print_info "usage: git clone-all <repository> [<directory>]"
 }
 
-clone()
-{
-	git clone --recurse-submodules -j 8 $repository $directory
-}
-
-check_arguments()
-{
-	if [ "$options" = "-h" ]
-	then 
-		print_help
-		exit 0
-	fi
-}
-options=$1
-
 set_tabs
 
-check_arguments "$1"
-repository=$1
-directory=$2
+SHORT=h
 
-clone
+# read the options
+OPTS=$(getopt -s sh --options $SHORT --name "$0" -- "$@")
+
+if [ $? != 0 ] ; then echo "Failed to parse options...exiting." >&2 ; exit 1 ; fi
+
+eval set -- "$OPTS"
+
+# extract options and their arguments into variables.
+while true ; do
+  case "$1" in
+	-h )
+      print_help
+	  exit 0
+      shift
+      ;;
+    -- )
+	  repository=$2
+	  directory=$3
+	  if [ -z $repository ]
+	  then
+		print_warning "Repository must be provided"
+		exit 1
+	  else
+		shift 2
+		if ! [ -z $directory ]
+  	    then
+  		  shift
+		fi
+	  fi
+      break
+      ;;
+    *)
+      break
+      ;;
+  esac
+done
+
+git clone --recurse-submodules -j8 $repository $directory
diff --git a/bin/git-commit-feature b/bin/git-commit-feature
--- a/bin/git-commit-feature
+++ b/bin/git-commit-feature
@@ -6,23 +6,31 @@ source "${SRC}/common/submodules.sh"
 print_help()
 {
 	print_info "Adds and commits all changes in root repository and all submodules."
-	print_info "<commit-message> will be prefixed with the current branch name."
+	print_info "If -m is used, the <commit-message> will be prefixed with the current branch name."
 	print_info "master: <commit-message>"
 	print_info ""
-	print_info "-c, --commit-only	only commits staged changes"
-	print_info "usage: git commit-feature [<options>] <commit-message>"
+	print_info "usage: git commit-feature [<options>]"
+	print_info ""
+	print_info "    -c, --commit-only	only commits staged changes"
+	print_info "    -m, --message <message>"
+	print_info "	commit message"
 }
 
 commit()
 {
-	if [ ! "$options" = "-c" ] && [ ! "$options" = "--commit-only" ]
+	if ! [ "$commit_only" = true ]
 	then 
 		print_info "Adding all changes" 
 		git add . || : 
 	fi
 	 
 	print_info "Committing all changes" 
-	git commit -m "$branch: $message"
+	if [ "$use_message" = true ]
+	then
+		git commit -m "$branch: $message"
+	else
+		git commit
+	fi
 }
 
 commit_submodules()
@@ -37,33 +45,51 @@ commit_submodules()
 	done
 }
 
-check_arguments()
-{
-	echo $1 " " $2
-	if [ $# -eq 0 ] || [ -z "$1" ]
-	then
-		print_error "<commit-message> is required"
-		print_help
-		exit 1
-	fi
+use_message=false
 
-	if [ "$options" = "-h" ]
-	then 
-		set_tabs
-		print_help
-		exit 0
-	fi
+set_tabs
 
-	if [ -z "$2" ]
-	then
-		message="$1"
-		options=''
-	fi
-}
-options="$1"
-message="$2"
+SHORT=chm:
+LONG=commit-only,message:
 
-check_arguments "$1" "$2"
+# read the options
+OPTS=$(getopt -s sh --options $SHORT --long $LONG --name "$0" -- "$@")
+
+if [ $? != 0 ] ; then echo "Failed to parse options...exiting." >&2 ; exit 1 ; fi
+
+eval set -- "$OPTS"
+
+# extract options and their arguments into variables.
+while true ; do
+  case "$1" in
+	-h )
+      print_help
+	  exit 0
+      shift
+      ;;
+    -m | --message )
+      message=$2
+	  use_message=true
+      shift 2
+      ;;
+	-c | --commit-only )
+      commit_only=true
+      shift 
+      ;;
+    -- )
+	  shift
+      ;;
+    *)
+      break
+      ;;
+  esac
+done
+
+if [ "$use_message" = true ] && [ -z "$message" ]
+then
+	print_warning "Message is required"
+	exit 1
+fi
 
 branch=$(git rev-parse --abbrev-ref HEAD)
 
diff --git a/bin/git-create-feature b/bin/git-create-feature
--- a/bin/git-create-feature
+++ b/bin/git-create-feature
@@ -8,27 +8,29 @@ source "${SRC}/common/common.sh"
 
 print_help()
 {
-	print_info "Creates a branch in root repository and all submodules based on the"
-	print_info "<master-branch> branch."
-	print_info "Checks out the new branch and pushes it to the remote. All local changes will remain."
+	print_info "Creates a branch in root repository and all submodules based"
+	print_info "the <master-branch> branch. Checks out the new branch and"
+	print_info "pushes it to the remote. All local changes is stashed/popped"
+	print_info "before/after creation."
 	print_info "" 
 	print_info "usage: git create-feature <feature-name> [<master-branch>]"
 }
 
 create_feature()
 {
+	print_info "In $1"
 	changes="$(git status --porcelain)"
-	if [ ! -z  "$changes"]
+	if ! [ -z  "$changes"]
 	then
 		print_info "Stashing changes"
 		git stash push
 	fi
 	print_info "Pull changes from remote"
 	git pull --rebase
-	print_info "Create branch $branch"
-	git checkout -b $branch
+	print_info "Create branch $feature_name"
+	git checkout -b $feature_name
     print_info "Push branch to remote"
-	git push -u origin $branch
+	git push -u origin $feature_name
 	
 	if [ ! -z "$changes"]
 	then
@@ -43,57 +45,56 @@ create_feature_submodules()
 	current_dir=$PWD
 	for submodule in $submodules_in_project; do
 		cd $submodule
-		print_info "In submodule $submodule"
-		create_feature
+		create_feature $submodule
 		cd $current_dir
 	done
 }
 
-check_arguments()
-{
-	if [ -z $options ]
-	then
-		print_error "Wrong arguments given!"
-		print_help
-		exit 0
-	fi
-
-	if [ "$options" == "-h" ]
-	then 
-		print_help && exit 0
-	fi
-
-	if [ -z $master_branch ]
-	then
-		master_branch=$2
-		branch=$1
-		options=''
-	fi
-
-	if [ -z $master_branch ]
-	then
-		print_info "Assuming branch master as <master-branch>"
-		master_branch="master"
-	fi
-
-	if [ -z $branch ]
-	then
-		print_error "<feature-name> is required"
-		print_help
-		exit 1
-	fi
-}
-
-options=$1
-branch=$2
-master_branch=$3
-
 set_tabs
 
-check_arguments "$1" "$2" "$3"
+SHORT=h
+
+# read the options
+OPTS=$(getopt -s sh --options $SHORT --name "$0" -- "$@")
+
+if [ $? != 0 ] ; then echo "Failed to parse options...exiting." >&2 ; exit 1 ; fi
+
+eval set -- "$OPTS"
+
+# extract options and their arguments into variables.
+while true ; do
+  case "$1" in
+	-h )
+      print_help
+	  exit 0
+      shift
+      ;;
+    -- )
+	  feature_name=$2
+	  master_branch=$3
+	  if [ -z $feature_name ]
+	  then
+		print_warning "<feature-name> must be provided"
+		exit 1
+	  fi
+	  shift 2
+	  if [ -z $master_branch ] 
+	  then
+		master_branch="master"
+		print_info "Assuming <master-branch> as 'master'"
+	  else
+		shift
+	  fi
+      break
+      ;;
+    *)
+      break
+      ;;
+  esac
+done
 
 print_info "Checking out $master_branch"
 git checkout-branch $master_branch
 
-create_feature &&
+create_feature "root" &&
 create_feature_submodules
diff --git a/bin/git-merge-feature b/bin/git-merge-feature
--- a/bin/git-merge-feature
+++ b/bin/git-merge-feature
@@ -6,10 +6,10 @@ source "${SRC}/common/submodules.sh"
 print_help()
 {
 	print_info "Merges <feature-branch> in root project and all submodules into <master-branch>."
+	print_info "If <master-branch> is not given it defaults to current branch."
 	print_info ""
-	print_info "usage: git merge-feature"
-	print_info "   or: git merge-feature <feature-branch>"
-	print_info "   or: git merge-feature <feature-branch> <master-branch>"
+	print_info "usage: git merge-feature <feature-branch>"
+	print_info "   or: git merge-feature <feature-branch> [<master-branch>]"
 }
 
 merge()
@@ -24,7 +24,7 @@ merge()
 	git pull --rebase
 	
 	print_info "Merge $feature into $master_branch"
-	git merge $feature
+	git merge --ff-only $feature
 }
 
 merge_submodules()
@@ -49,39 +49,50 @@ push_master_and_remove_feature()
 	git remove-feature $feature
 }
 
-check_arguments()
-{
-	if [ "$options" == "-h" ]
-	then 
-		print_help
-		exit 0
-	fi
-
-	if [ -z $master_branch ]
-	then
-		feature=$1
-		master_branch=$2
-		options=''
-	fi
-	
-	if [ -z $master_branch ]
-	then
-		master_branch="master"
-	fi
-	
-	if [ -z $feature ]
-	then
-		feature=$(git rev-parse --abbrev-ref HEAD)
-	fi
-}
-
-options=$1
-feature=$2
-master_branch=$3
-
 set_tabs
 
-check_arguments "$1" "$2" "$3"
+SHORT=h
+
+number_of_commits=-1
+
+# read the options
+OPTS=$(getopt -s sh --options $SHORT --name "$0" -- "$@")
+
+if [ $? != 0 ] ; then echo "Failed to parse options...exiting." >&2 ; exit 1 ; fi
+
+eval set -- "$OPTS"
+
+# extract options and their arguments into variables.
+while true ; do
+  case "$1" in
+	-h )
+      print_help
+	  exit 0
+      shift
+      ;;
+    -- )
+	  feature=$2
+	  master_branch=$3
+	  if [ -z $feature ]
+	  then
+		print_warning "Feature branch must be provided"
+		exit 1
+	  fi
+	  shift 2
+	  if [ -z $master_branch ]
+		then
+			master_branch=$(git rev-parse --abbrev-ref HEAD)
+			print_info "Assuming branch $master_branch as master-branch"
+		else
+			shift
+		fi
+      break
+      ;;
+    *)
+      break
+      ;;
+  esac
+done
 
 merge &&
 merge_submodules &&
diff --git a/bin/git-push-feature b/bin/git-push-feature
--- a/bin/git-push-feature
+++ b/bin/git-push-feature
@@ -6,15 +6,25 @@ source "${SRC}/common/submodules.sh"
 print_help()
 {
 	print_info "Push all changes in root repository and all submodules."
-	print_info "The push is made with -f flag."
 	print_info ""
-	print_info "usage: git push-feature"
+	print_info "usage: git push-feature [<options>] [<remote>]"
+	print_info ""
+	print_info "    -f, --force	force updates"
+	print_info "    --force-with-lease	forces update if ok"
 }
 
 push()
 {
 	print_info "Pushing $1"
-	git push -f
+	if [ "$force" = true ]
+	then
+		git push -f $remote
+	elif [ "$force_with_lease" = true ]
+	then
+		git push --force-with-lease $remote
+	else
+		git push $remote
+	fi
 }
 
 push_submodules()
@@ -37,11 +47,51 @@ check_arguments()
 	fi
 }
 
-options=$1
-
 set_tabs
 
-check_arguments
+SHORT=fh
+LONG=force,force-with-lease
+
+# read the options
+OPTS=$(getopt -s sh --options $SHORT --long $LONG --name "$0" -- "$@")
+
+if [ $? != 0 ] ; then echo "Failed to parse options...exiting." >&2 ; exit 1 ; fi
+
+eval set -- "$OPTS"
+
+# extract options and their arguments into variables.
+while true ; do
+  case "$1" in
+	-h )
+      print_help
+	  exit 0
+      shift
+      ;;
+    -f | --force )
+      force=true
+      shift
+      ;;
+    --force-with-lease )
+      force_with_lease=true
+      shift
+      ;;
+    -- )
+		remote=$2
+		if [ -z $remote ]
+		then
+			print_info "Assuming origin as default remote"
+			remote="origin"
+		else
+			shift
+		fi
+		shift
+      break
+      ;;
+    *)
+      break
+      ;;
+  esac
+done
 
 push "root" &&
 push_submodules
diff --git a/bin/git-rebase-feature b/bin/git-rebase-feature
--- a/bin/git-rebase-feature
+++ b/bin/git-rebase-feature
@@ -157,47 +157,51 @@ rebase_done()
 	rm .git/SUBMODULES_DONE
 }
 
-check_arguments()
-{
-	if [ $# -eq 0 ]
-	then
-		print_warning "<feature-branch> and <rebase-branch> are required"
-		print_help
-		exit 1
-	fi
-
-	if [ "$1" == "-h" ]
-	then 
-		print_help
-		exit 0
-	fi
-
-	if [ -z $rebase_branch ]
-	then
-		rebase_branch=$2
-		feature_branch=$1
-		options=''
-	fi
-
-	if [ -z $rebase_branch ]
-	then
-		print_warning "feature-branch and rebase-branch is required"
-		print_help
-		exit 1
-	fi
-}
-
-options=$1
-feature_branch=$2
-rebase_branch=$3
-
 set_tabs
+
+SHORT=ch
+LONG=continue
+
+# read the options
+OPTS=$(getopt -s sh --options $SHORT --long $LONG --name "$0" -- "$@")
+
+if [ $? != 0 ] ; then echo "Failed to parse options...exiting." >&2 ; exit 1 ; fi
+
+eval set -- "$OPTS"
+
+# extract options and their arguments into variables.
+while true ; do
+  case "$1" in
+	-h )
+      print_help
+	  exit 0
+      shift
+      ;;
+    -c | --continue )
+      continue=true
+      shift
+      ;;
+    -- )
+	  if [ -z $2 ] || [ -z $3 ]
+	  then
+		print_warning "Both feature-branch and rebase-branch must be provided"
+		exit 1
+	  else
+		feature_branch=$2
+		rebase_branch=$3
+	  fi
+	  shift 3
+      break
+      ;;
+    *)
+      break
+      ;;
+  esac
+done
 
 starting_mergetool="Starting mergetool"
 
-check_arguments "$1" "$2" "$3"
-
-if [ -z $options ]
+if ! [ "$continue" = true ]
 then
 	if [ -e .git/SUBMODULES_DONE ] 
 	then 
@@ -213,7 +217,7 @@ then
 	reset_submodules &&
 	push_root && 
 	rebase_done
-elif [ "$options" == "-c" ] || [ "$options" == "--continue" ]
+elif [ "$continue" = true ]
 then
 	if [ -e .git/SUBMODULES_DONE ] 
 	then 
diff --git a/bin/git-remove-feature b/bin/git-remove-feature
--- a/bin/git-remove-feature
+++ b/bin/git-remove-feature
@@ -8,17 +8,30 @@ print_help()
 	print_info "Removes the <feature-branch> in root repository and all submodules."
 	print_info "Both local and remote."
 	print_info ""
-	print_info "usage: git remove-feature <feature-branch>"
+	print_info "usage: git remove-feature [<options>] <feature-branch> [<remote>]"
+	print_info ""
+	print_info "    -f, --force	remove even if branch not merged"
+	print_info "    -l, --local-only	local and remote ref removed"
+	
 }
 
 remove_branch()
 {
+	d_flag="-d"
+	if [ "$force" = true ]
+	then
+		print_info "Forcing deletion of branch"
+		d_flag="-D"
+	fi
 	print_info "Remove local branch $feature in $1"
-	git branch -D $feature
-	print_info "Remove remote reference to branch $feature in $1"
-	git branch -D -r origin/$feature
-	print_info "Remove remote branch $feature in $1"
-	git push -d origin $feature
+	git branch $d_flag $feature
+	print_info "Remove remote reference to $remote/$feature in $1"
+	git branch $d_flag -r $remote/$feature
+	if ! [ "$local_only" = true ]
+	then
+		print_info "Remove remote branch $feature in $1 on $remote"
+		git push -d $remote $feature
+	fi
 }
 
 remove_submodules_branch()
@@ -32,33 +45,68 @@ remove_submodules_branch()
 	done
 }
 
-check_arguments()
-{
-	if [ -z $feature ]
-	then
-		print_error "<feature-branch> is required"
-		print_help
-		exit 1
-	fi
-	
-	if [ "$1" == "-h" ]
-	then
-		print_help
-		exit 0
-	fi
-	
-	if [ "$feature" == "master" ]
-	then
-		print_warning "Branch master will not be removed!"
-		exit 1
-	fi
-}
-
-feature=$1
-
 set_tabs
 
-check_arguments "$1"
+SHORT=flh
+LONG=force,local-only
+
+# read the options
+OPTS=$(getopt -s sh --options $SHORT --long $LONG --name "$0" -- "$@")
+
+if [ $? != 0 ] ; then echo "Failed to parse options...exiting." >&2 ; exit 1 ; fi
+
+eval set -- "$OPTS"
+
+# extract options and their arguments into variables.
+while true ; do
+  case "$1" in
+	-h )
+      print_help
+	  exit 0
+      shift
+      ;;
+    -f | --force )
+      force=true
+      shift
+      ;;
+    -l | --local-only )
+      local_only=true
+      shift
+      ;;
+    -- )
+		feature=$2
+		remote=$3
+		if [ -z $feature ]
+		then
+			print_warning "<feature-branch> is required"
+			exit 1
+		fi
+		if [ "$feature" == "master" ]
+		then
+			print_warning "Branch master can not be removed!"
+			exit 1
+		fi
+		shift 2
+		
+		if  branch_exist "$feature"
+		then
+			print_warning "Branch '$feature' not found"
+			exit 1
+		fi
+		if [ -z $remote ]
+		then
+			print_info "Assuming origin as default remote"
+			remote="origin"
+		else
+			shift
+		fi
+      break
+      ;;
+    *)
+      break
+      ;;
+  esac
+done
 
 remove_branch "root"
 remove_submodules_branch
diff --git a/bin/git-status-all b/bin/git-status-all
--- a/bin/git-status-all
+++ b/bin/git-status-all
@@ -7,13 +7,31 @@ print_help()
 {
 	print_info "Shows the status for the root repository and all submodules."
 	print_info ""
-	print_info "usage: git status-all"
+	print_info "usage: git status-all [<options>]"
+	print_info ""
+	print_info "    -s, --short	show status concisely"
+	print_info "    -u, --untracked-files[=<mode>]"
+    print_info "	show untracked files, optional modes: all, normal, no. (Default: all)"
 }
 
 status()
 {
 	print_info "Status in $1" 
-	git status -su || :  
+	if [ "$short" = true ]
+	then
+		short_flag="-s"
+	fi
+	
+	if [ "$untracked_files" = true ]
+	then
+		if [ -z $untracked_mode ]
+		then
+			untracked_flag="-u"
+		else
+			untracked_flag="-u$untracked_mode"
+		fi
+	fi
+	git status $short_flag $untracked_flag || :  
 }
 
 status_submodules()
@@ -27,19 +45,48 @@ status_submodules()
 	done
 }
 
-check_arguments()
-{
-	if [ "$options" = "-h" ]
-	then 
-		print_help
-		exit 0
-	fi
-}
-options=$1
-
 set_tabs
 
-check_arguments "$1"
+SHORT=hsu::
+LONG=short,untracked-files::
+
+# read the options
+OPTS=$(getopt -s sh --options $SHORT --long $LONG --name "$0" -- "$@")
+
+if [ $? != 0 ] ; then echo "Failed to parse options...exiting." >&2 ; exit 1 ; fi
+
+eval set -- "$OPTS"
+
+# extract options and their arguments into variables.
+while true ; do
+  case "$1" in
+	-h )
+      print_help
+	  exit 0
+      shift
+      ;;
+    -s | --short )
+      short=true
+      shift
+      ;;
+    -u | --untracked-files )
+      untracked_files=true
+	  untracked_mode=$2
+	  if ! [ -z $untracked_mode ]
+	  then
+		shift
+	  fi
+      shift
+      ;;
+    -- )
+      shift
+      break
+      ;;
+    *)
+      break
+      ;;
+  esac
+done
 
 status "root" 
 status_submodules
diff --git a/bin/git-sync-branch b/bin/git-sync-branch
--- a/bin/git-sync-branch
+++ b/bin/git-sync-branch
@@ -9,9 +9,12 @@ source "${SRC}/common/common.sh"
 print_help()
 {
 	print_info "Checks out <branch> and pulls the latest changes for <branch> in root repository"
-	print_info "and all submodules."
+	print_info "and all submodules, using rebase."
 	print_info "" 
-	print_info "usage: git sync-branch <branch>"
+	print_info "usage: git sync-branch [<options>] [<remote> [<branch>]]"
+	print_info ""
+	print_info "    -a, --autostash	automatically stash/stash pop before and after rebase" 
+	print_info "    --fetch-only	performs a fetch instead of pull --rebase" 
 }
 
 sync_branch()
@@ -22,7 +25,16 @@ sync_branch()
 	then
 		return 1
 	fi
-	git pull --rebase
+	if [ "$autostash" = true ]
+	then
+		a_flag="--autostash"
+	fi
+	if [ "$fetch_only" = true ]
+	then
+		git fetch $remote $branch
+	else
+		git pull $a_flag --rebase $remote
+	fi
 	return 0
 }
 
@@ -32,33 +44,63 @@ sync_branch_submodules()
 	current_dir=$PWD
 	for submodule in $submodules_in_project; do
 		cd $submodule
-		print_info "In submodule $submodule"
 		sync_branch $submodule
 		cd $current_dir
 	done
 }
 
-check_parameters()
-{
-	if [ -z $1 ]
-	then
-		print_error "<branch> is required"
-		print_help
-		exit 1
-	fi
-	
-	if [ "$1" == "-h" ]
-	then
-		print_help
-		exit 0
-	fi
-}
-
 set_tabs
 
-branch=$1
+SHORT=ah
+LONG=autostash,fetch-only
 
-check_parameters "$1"
+# read the options
+OPTS=$(getopt -s sh --options $SHORT --long $LONG --name "$0" -- "$@")
+
+if [ $? != 0 ] ; then echo "Failed to parse options...exiting." >&2 ; exit 1 ; fi
+
+eval set -- "$OPTS"
+
+# extract options and their arguments into variables.
+while true ; do
+  case "$1" in
+	-h )
+      print_help
+	  exit 0
+      shift
+      ;;
+    -a | --autostash )
+      autostash=true
+      shift
+      ;;
+    --fetch-only )
+      fetch_only=true
+      shift
+      ;;
+    -- )
+	  remote=$2
+	  branch=$3
+	  if ! [ -z $remote ]
+	  then
+		shift 2
+		if [ -z $branch ]
+		then
+		  branch=$(git rev-parse --abbrev-ref HEAD)
+		  print_info "Assuming current branch $branch as <branch>"
+		else
+			shift
+		fi
+	  else
+	    branch=$(git rev-parse --abbrev-ref HEAD)
+		print_info "Assuming current branch $branch as <branch>"
+	  fi
+      break
+      ;;
+    *)
+      break
+      ;;
+  esac
+done
 
 sync_branch "root" && 
 sync_branch_submodules
